workflows:
  version: 2
  dev_stage_pre-prod:
      jobs:
      - flow

      - test_stage:
          requires:
            - flow
          filters:
            branches:
              only:
                - /dev-.*/
                - /fix-.*/
                - /chore-.*/

      - test_pre-prod:
          requires:
            - flow
          filters:
            branches:
              only:
                - master

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:10-stretch

version: 2
jobs:

  flow:
    <<: *defaults

    steps:
      - checkout

      - run: cp src/services/config.js.example src/services/config.js

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: yarn install

      - run: yarn build

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run:
          command: |
            npm install --save-dev --save-exact ava@next
            npm install tap-xunit --save-dev # or you could use npm
            mkdir -p ~/reports
            yarn test:ci | npx tap-xunit > ~/reports/ava.xml
          when: always
      - store_test_results:
          path: ~/reports
      - store_artifacts:
          path: ~/reports


  # test-dev:
  #   <<: *defaults
  #   steps:
  #     - checkout
  #     - run: ./node_modules/.bin/firebase deploy --token $FIREBASE_TOKEN
  test_stage:
    <<: *defaults
    steps:
      - checkout

      - run:                                                                                                   #
          name: Run setup script                                                                               #
          command: bash .circleci/setup-heroku.sh                                                              #
      - add_ssh_keys:                                                                                          #
          ## Added pub key to heroku && added priv key under Circle SSH PERMISSIONS (no passph)                #
          fingerprints:                                                                                        #
            - "71:f5:71:db:2f:95:9a:da:ff:64:e6:cd:63:d9:3e:ba"                                                #

      - run: git push -f git@heroku.com:${HEROKU_APP_STAGING}.git ${CIRCLE_BRANCH}:master

  test_pre-prod:
    <<: *defaults
    steps:
      - checkout

      - run: yarn install

      - run: yarn build

      # run tests!
      - run:
          command: |
            npm install --save-dev --save-exact ava@next
            npm install tap-xunit --save-dev # or you could use npm
            mkdir -p ~/reports
            yarn test:ci | npx tap-xunit > ~/reports/ava.xml
          when: always
      - store_test_results:
          path: ~/reports
      - store_artifacts:
          path: ~/reports

      - run: npm install --save-dev firebase-tools

      - run: npx firebase deploy --token $FIREBASE_TOKEN
