workflows:
  version: 2
  dev_stage_pre-prod:
      jobs:
      - flow

      - test_stage:
          requires:
            - flow
          filters:
            branches:
              only:
                - /dev-.*/
                - /fix-.*/
                - /chore-.*/

      - test_pre-prod:
          requires:
            - flow
          filters:
            branches:
              only:
                - master

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:10-stretch

version: 2
jobs:

  flow:
    <<: *defaults

    steps:
      - checkout

      # Download and cache dependencies

      - run: yarn install
      - run: yarn build
  test_stage:
    <<: *defaults


    steps:
      - checkout

      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - node-v1-{{ .Branch }}-
            - node-v1-




      # - run: yarn test

      - run:                                                                                                   #
          name: Run setup script                                                                               #
          command: bash .circleci/setup-heroku.sh                                                              #
      - add_ssh_keys:                                                                                          #
          ## Added pub key to heroku && added priv key under Circle SSH PERMISSIONS (no passph)                #
          fingerprints:                                                                                        #
            - "71:f5:71:db:2f:95:9a:da:ff:64:e6:cd:63:d9:3e:ba"                                                #

      - run: git push -f git@heroku.com:${HEROKU_APP_STAGING}.git ${CIRCLE_BRANCH}:master
      - save_cache:
          paths:
            # - node_modules
            - ~/usr/local/lib/node_modules  # location depends on npm version
          key: node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}



  test_pre-prod:
    <<: *defaults
    steps:
      - checkout

      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - node-v1-{{ .Branch }}-
            - node-v1-




      - run: rm -rf node_modules


      - run: yarn install

      - run: yarn build

      - run: npm install --save-dev firebase-tools

      - run: npx firebase deploy --token $FIREBASE_TOKEN

      - save_cache:
          paths:
            # - node_modules
            - ~/usr/local/lib/node_modules  # location depends on npm version
          key: node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
